<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit"/>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="SkiaSharp"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Chaos.Client\Chaos.Client.csproj"/>
    </ItemGroup>

</Project>
